#!/usr/bin/env node
/**
 * Generate the SCSS theme-tokens partial from the single tokens manifest
 * (`shared/theme/tokens.ts`) — the "Style Dictionary" formatter step (audit §5.5).
 *
 * One manifest → two outputs: the TS side is imported directly by the app/server
 * (`PRESETS`, `THEME_BACKGROUNDS`); this script emits the SCSS side so background
 * image paths and Reveal dimensions are declared exactly once. The generated
 * partial only EXPOSES values as namespaced CSS custom properties under
 * `:root` — it never overrides a theme's existing color/layout rules, so it is
 * additive and safe to regenerate on every build.
 *
 * Runs via Node's native TypeScript type-stripping (Node ≥ 23), so it can import
 * the `.ts` manifest with no build step.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { THEME_TOKENS } from '../shared/theme/tokens.ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = join(__dirname, '..')
const outPath = join(projectRoot, 'themes/shared/_tokens.generated.scss')

function cssVarsForTheme(tokens) {
  const lines = []
  const bg = tokens.backgrounds ?? {}
  for (const level of ['h1', 'h2', 'h3', 'default']) {
    if (bg[level])
      lines.push(`    --bg-${level}: url('${bg[level]}');`)
  }
  const reveal = tokens.reveal ?? {}
  if (reveal.width != null)
    lines.push(`    --deck-width: ${reveal.width};`)
  if (reveal.height != null)
    lines.push(`    --deck-height: ${reveal.height};`)
  return lines
}

function generate() {
  const blocks = Object.values(THEME_TOKENS).map((tokens) => {
    const vars = cssVarsForTheme(tokens)
    if (vars.length === 0)
      return `  // ${tokens.name}: no background/dimension tokens`
    return [
      `  // ${tokens.name}`,
      `  :root[data-theme='${tokens.name}'],`,
      `  .theme-${tokens.name} {`,
      ...vars,
      `  }`,
    ].join('\n')
  })

  const content = `// AUTO-GENERATED by scripts/build-theme-tokens.ts — DO NOT EDIT.
// Source of truth: shared/theme/tokens.ts (audit §5.5).
// Exposes background image paths and deck dimensions as CSS custom properties,
// so the SCSS and TS sides are generated from one manifest. Additive only:
// defines a mixin a theme opts into with \`@include tokens.theme-tokens;\` —
// emits nothing by itself, so existing compiled CSS is unaffected.

@mixin theme-tokens {
${blocks.join('\n\n')}
}
`

  mkdirSync(dirname(outPath), { recursive: true })
  writeFileSync(outPath, content)

  console.log(`✓ Generated ${outPath.replace(`${projectRoot}/`, '')} from theme tokens manifest`)
}

generate()
